/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens (from Stitch design system)
        'surface': '#fdf9f2',
        'surface-bright': '#fdf9f2',
        'surface-dim': '#dddad3',
        'surface-variant': '#e6e2db',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ec',
        'surface-container': '#f1ede6',
        'surface-container-high': '#ece8e1',
        'surface-container-highest': '#e6e2db',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#434842',
        'inverse-surface': '#31302c',
        'inverse-on-surface': '#f4f0e9',
        'surface-tint': '#536252',
        'primary': '#536252',
        'primary-container': '#6b7b6a',
        'primary-fixed': '#d6e7d3',
        'primary-fixed-dim': '#bacbb8',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'on-primary-fixed': '#111f12',
        'on-primary-fixed-variant': '#3c4b3c',
        'inverse-primary': '#bacbb8',
        'secondary': '#7c544f',
        'secondary-container': '#ffcbc4',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#edbbb3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#7b534e',
        'on-secondary-fixed': '#2f1310',
        'on-secondary-fixed-variant': '#613d38',
        'tertiary': '#735b24',
        'tertiary-container': '#8e733a',
        'tertiary-fixed': '#ffdf9f',
        'tertiary-fixed-dim': '#e3c281',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5a430e',
        'outline': '#747872',
        'outline-variant': '#c4c8c0',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#fdf9f2',
        'on-background': '#1c1c18',
        // Philosopher accent colors
        'freud': '#A0522D',
        'anna-freud': '#718096',
        'afreud': '#718096',
        'winnicott': '#40916C',
        'jung': '#8B6914',
        'klein': '#9B59B6',
        'lacan': '#2E6DA4',
        // Brand
        'brand-forest': '#2F3A34',
        'brand-gold': '#C8A96A',
        'brand-ivory': '#F5F1EA',
        'brand-olive': '#6B7B6A',
        'brand-taupe': '#4A4541',
        'brand-rose': '#D8A7A0',
      },
      fontFamily: {
        'headline': ['Newsreader', 'serif'],
        'body': ['Newsreader', 'serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.0625rem',
        'md': '0.375rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '1rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
